### ISSUE TITLE
Does not seem to work for using a tilemap to mask another tilemask

### ISSUE THREAD

**Issue by BlueAwesomeDinosaur** [justcore69/UnityTilemapMask#1]
Hi. Thank you so much for the script, but it does not seem to work when I use a tilemap as a mask for another tilemap. What could I be doing wrong? Images are attached.

![image](https://github.com/CalmlyGrass/UnityTilemapMask/assets/88523101/cb556841-9011-4335-97f1-e45c528d2b1c)
![image](https://github.com/CalmlyGrass/UnityTilemapMask/assets/88523101/2fd880fb-95d9-4daa-afd5-8656517837ef)
The cliffmask is supposed to mask off the walls so only parts in the mask appear. However, it seems that the mask makes the walls disappear completely.

**Comment by justcoredev** [comment]
Thank you for highlighting the issue. I've pinpointed and fixed a code problem that prevented correct mask generation. The updated script now properly generates masks at all times. Download the latest files from the repo and see the updated README for guidance. Text here if you will encounter any other issues!

**Comment by BlueAwesomeDinosaur** [comment]
Thank you so much! It works very well now! The only thing I've had to change is to add a custom range for the prefab used so it does not interfere with other similar masks. It may be helpful to add that as a value you can pass in the script but it should work fine just modifying the prefab.
Edit: Tested it just now. Modifying the prefab works out perfectly. Thanks again!

**Comment by justcoredev** [comment]
Probably I'll make some layer system later. This repo is already 2 years old, and I think it really needs some improvements! :)
Thanks for this issue again, I think I can close it now
